// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl5i2E67PI9911jtw9LZR0u4Ny50vLR0w',
    appId: '1:94385791237:web:495070a6c7b24b6a2d576c',
    messagingSenderId: '94385791237',
    projectId: 'betteredu-website',
    authDomain: 'betteredu-website.firebaseapp.com',
    storageBucket: 'betteredu-website.appspot.com',
    measurementId: 'G-ZZH5X20207',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1SvuKHnQnftOghdVJ-rxjwZSRJtrErFk',
    appId: '1:94385791237:android:ec62388a0854a9e22d576c',
    messagingSenderId: '94385791237',
    projectId: 'betteredu-website',
    storageBucket: 'betteredu-website.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbOi91uL_8fcGMo0Mk34KVKK96_iI87HI',
    appId: '1:94385791237:ios:91fd37e5fc779c932d576c',
    messagingSenderId: '94385791237',
    projectId: 'betteredu-website',
    storageBucket: 'betteredu-website.appspot.com',
    iosClientId: '94385791237-752dlqu7vvntau95j76g8idl90dp82b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.plswork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbOi91uL_8fcGMo0Mk34KVKK96_iI87HI',
    appId: '1:94385791237:ios:16756642884d395b2d576c',
    messagingSenderId: '94385791237',
    projectId: 'betteredu-website',
    storageBucket: 'betteredu-website.appspot.com',
    iosClientId: '94385791237-2dd04aegpaj1pkl2s50nh5sqpv9stbjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.plswork.RunnerTests',
  );
}
